### ISSUE TITLE
Documentation issue on page "https://github.com/freegroup/kube-https.git"

### ISSUE THREAD

**Issue by BRuhland** [freegroup/kube-https#1]
Following exactly the documentation and using the example *.json file content, the command described here is failing:

cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server server.json | cfssljson -bare server
2018/08/15 09:16:47 [INFO] generate received request
2018/08/15 09:16:47 [INFO] received CSR
2018/08/15 09:16:47 [INFO] generating key: rsa-2048
2018/08/15 09:16:48 [INFO] encoded CSR
{"code":5100,"message":"Invalid policy: no key usage available"}
Failed to parse input: unexpected end of JSON input

---
Page: [https://github.com/freegroup/kube-https.git](https://github.com/freegroup/kube-https.git)
don't remove the link to the page. It's required for the processor

**Comment by freegroup** [comment]
It is working well on my side. I tested this setup right now and everything is ok. CERTS generated.

```
WDFM33957623A:cfssl d023280$ cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server server.json | cfssljson -bare server
2018/08/15 11:41:42 [INFO] generate received request
2018/08/15 11:41:42 [INFO] received CSR
2018/08/15 11:41:42 [INFO] generating key: rsa-2048
2018/08/15 11:41:42 [INFO] encoded CSR
2018/08/15 11:41:42 [INFO] signed certificate with serial number 189732853523697708208635600794677692735950207039

```


Maybe your JSON is broken? some typo?

**Comment by BRuhland** [comment]
As copy and paste from documentation it should be fine. Never the less find attached the json files generated according documentation.

 

Thx

Bernd

 

Bernd Ruhland


Cloud Foundry Lab, PI Technology EngSrv Production (SE)
SAP SE, Dietmar-Hopp-Allee 16, 69190, Walldorf, Germany

T +49 6227 7-45372, M +49 160 90432483, E bernd.ruhland@sap.com

Pflichtangaben/Mandatory Disclosure Statement:
http://www.sap.com/company/legal/impressum.epx/ <http://www.sap.com/company/legal/impressum.epx>  

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts, eine Vervielfältigung oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail.
Vielen Dank. 

This e-mail may contain trade secrets or privileged, undisclosed, or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying, or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal.
Thank you for your cooperation

**Comment by freegroup** [comment]
wrong JSON from user. *www* instead of *server* in configuration
